"""SKU aliasing: 21 listings on this account are held with a zero
prepended to our SKU, so writes must go out under the platform's SKU and
reads must come back under ours. A wrong alias would push one product's
price and stock onto another product's listing, so the ambiguity rules
here matter more than the happy path."""
import csv
import io
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import sku_aliases  # noqa: E402

ALIAS_CSV = Path(__file__).resolve().parents[1] / "sku_aliases.csv"


def _write(tmp_path, rows):
    p = tmp_path / "aliases.csv"
    with io.open(p, "w", encoding="utf-8", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["true_sku", "onbuy_sku", "opc", "recorded"])
        for r in rows:
            w.writerow(r)
    return p


def test_translates_both_directions(tmp_path):
    p = _write(tmp_path, [("371763399077", "0371763399077", "PXB8YSP", "2026-09-03")])
    fwd, rev = sku_aliases.load_aliases(str(p))
    assert fwd["371763399077"] == "0371763399077"
    assert rev["0371763399077"] == "371763399077"


def test_two_skus_claiming_one_listing_are_dropped(tmp_path):
    # Aliasing either one would write to whichever product won the
    # collision, so neither may be aliased.
    p = _write(tmp_path, [("922051131758", "922050000000", "PXM287R", "x"),
                          ("922049922412", "922050000000", "PXM287R", "x")])
    fwd, rev = sku_aliases.load_aliases(str(p))
    assert fwd == {} and rev == {}


def test_one_sku_claiming_two_listings_is_dropped(tmp_path):
    p = _write(tmp_path, [("111111111111", "111111000000", "A", "x"),
                          ("111111111111", "111112000000", "B", "x")])
    fwd, _ = sku_aliases.load_aliases(str(p))
    assert fwd == {}


def test_identity_rows_are_not_aliases(tmp_path):
    p = _write(tmp_path, [("123456789012", "123456789012", "A", "x")])
    fwd, rev = sku_aliases.load_aliases(str(p))
    assert fwd == {} and rev == {}


def test_missing_file_is_not_fatal(tmp_path):
    fwd, rev = sku_aliases.load_aliases(str(tmp_path / "nope.csv"))
    assert (fwd, rev) == ({}, {})


def test_unknown_skus_pass_straight_through():
    assert sku_aliases.to_onbuy("999999999999") == "999999999999"
    assert sku_aliases.to_true("999999999999") == "999999999999"
    assert sku_aliases.to_onbuy("") == ""
    assert sku_aliases.to_onbuy(None) == ""


def test_shipped_file_is_unambiguous_and_well_formed():
    """The file the pipeline actually loads - regenerated by
    probe_sku_rounding.py, so pin its shape rather than its contents."""
    rows = list(csv.DictReader(io.open(ALIAS_CSV, encoding="utf-8-sig")))
    assert rows, "alias file is empty"
    trues = [r["true_sku"].strip() for r in rows]
    stored = [r["onbuy_sku"].strip() for r in rows]
    assert len(set(trues)) == len(trues), "a SKU is aliased twice"
    assert len(set(stored)) == len(stored), "two SKUs claim one listing"
    assert not set(trues) & set(stored), "an alias target is also a real SKU"
    for t, s in zip(trues, stored):
        assert t.isdigit() and s.isdigit(), f"non-numeric pair {t}/{s}"
        assert t != s


def test_loaded_map_matches_the_shipped_file():
    rows = list(csv.DictReader(io.open(ALIAS_CSV, encoding="utf-8-sig")))
    assert len(sku_aliases.TO_ONBUY) == len(rows)
    assert len(sku_aliases.TO_TRUE) == len(rows)
