name: Test Create Product

on:
  workflow_dispatch:

jobs:
  create-product:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install requests

      - name: Create Product (sandbox)
        env:
          ONBUY_TEST_CONSUMER_KEY: ${{ secrets.ONBUY_TEST_CONSUMER_KEY }}
          ONBUY_TEST_SECRET_KEY: ${{ secrets.ONBUY_TEST_SECRET_KEY }}
          ONBUY_SELLER_ID: ${{ secrets.ONBUY_SELLER_ID }}
          ONBUY_SITE_ID: ${{ secrets.ONBUY_SITE_ID }}
        run: python test_create_product.py
